version: '3.9'

services:
  postgres-docker:
    container_name: postgres-docker
    image: postgres
    tty: true
    stdin_open: true
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
